### ISSUE TITLE
Can repeatedly mint stories with no auction winner

### ISSUE THREAD

**Issue by EzraWeller** [SquadGames/Aavenluutn#10]
Testing the frontend with the existing deployment (using the `frontend` branch), which has ~6 stories that all completed without having any bids, I seem to be able to mint myself the NFTs any number of times:
- https://ropsten.etherscan.io/tx/0x01d1e1c97fca64afd63e87b4b01b57eeaac59cd326112c77e5ceb5e147afa590
- https://ropsten.etherscan.io/tx/0x0b834918f82057ee39e48552d7a968a59ee849b714d3bfd140033bf1095f2bc5

**Comment by jessebmiller** [comment]
Sounds plausible. I'll take a look

**Comment by jessebmiller** [comment]
Fixed
